---
title: "My first dashboard" 
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
# load data
data("instacart")

set.seed(1)

data(instacart)
instacart = 
  instacart %>% 
  # select only a few columns
  select(reordered, order_dow, order_hour_of_day, days_since_prior_order, product_name, aisle) %>%
  # mutate order_dow as day of the week
  mutate(order_dow = as.factor(order_dow),
         order_dow = recode(order_dow, 
                            "0" = "Sun", "1" = "Mon", "2" = "Tue", "3" = "Wed", 
                            "4" = "Thu", "5" = "Fri", "6" = "Sat")) %>% 
  # focus on fresh fruits
  filter(aisle %in% c("fresh fruits")) %>% 
# only need 500 samples  
sample_n(500)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  # calculate total reordered times for each 
  group_by(product_name) %>% 
  summarise(reordered_times = sum(reordered)) %>% 
  # keep only reordered times > 5
  filter(reordered_times > 5) %>% 
  # reorder the number of times from low to high
  mutate(product_name = fct_reorder(product_name, reordered_times)) %>% 
  # plotly
  plot_ly(x = ~product_name, y = ~reordered_times, type = "bar") %>% 
  # add labels
  layout(title = "Number of times that a fresh fruit has been reordered.", xaxis = list(title  = "product name"), yaxis = list(title = "reordered times"))
```

### Chart B

```{r}
instacart %>% 
  # calculate total reordered times for each
  group_by(product_name) %>%
  mutate(reordered_times = sum(reordered)) %>% 
  # keep only reordered times > 10
  filter(reordered_times > 10) %>%
  # plotly
  plot_ly(x = ~product_name, y = ~order_hour_of_day, type = "box", color = ~product_name, colors = "Set2") %>% 
  # add labels
  layout(title = "Hour of the day that a fresh fruit is ordered.", xaxis = list(title  = "product name"), yaxis = list(title = "hour of the day"))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}
# day of the week vs reordered times
# keep only reordered times > 5
dow_data =
  instacart %>% 
  group_by(order_dow) %>% 
  summarize(reordered_times = sum(reordered)) %>% 
  filter(reordered_times > 5) 

# plotly, scatter+line
plot_ly(dow_data, x= ~order_dow, y = ~reordered_times, type = "scatter", mode = "markers") %>% 
  add_lines(showlegend=FALSE) %>% 
  # add labels
  layout(title = "Day of the week vs reordered times.", xaxis = list(title  = "day of the week"), yaxis = list(title = "reordered times"))
```

### Chart D
```{r}
# hour of the day vs reordered times
# keep only reordered times > 5
hod_data = 
  instacart %>% 
  group_by(order_hour_of_day) %>% 
  summarize(reordered_times = sum(reordered)) %>% 
  filter(reordered_times > 5) 

# plotly, scatter+line
plot_ly(hod_data, x= ~order_hour_of_day, y = ~reordered_times, type = "scatter", mode = "markers") %>% 
  add_lines(showlegend=FALSE) %>% 
  # add labels
  layout(title = "Hour of the day vs reordered times.", xaxis = list(title  = "hour of the day"), yaxis = list(title = "reordered times"))
```
